app = 'rootfrontend'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.routes]]
    match = "/api/*"
    destination = "https://rootbackend.fly.dev"  # ⬅️ ton backend Fly ici

  [[http_service.routes]]
    match = "/*"
    destination = "/index.html"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
